# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticies', '0002_auto_20160920_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('titol_categoria', models.CharField(max_length=50, verbose_name='Titol de la categoria')),
            ],
            options={
                'ordering': ['titol_categoria'],
            },
        ),
    ]
