# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_auto_20160920_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='centre',
            fields=[
                ('id_centre', models.AutoField(primary_key=True, serialize=False)),
                ('nom_centre', models.CharField(max_length=50)),
                ('ciutat_centre', models.CharField(max_length=20)),
                ('cp_centre', models.CharField(max_length=5)),
                ('mail_centre', models.EmailField(max_length=80)),
            ],
            options={
                'ordering': ['nom_centre'],
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo_empresa',
            field=models.ImageField(blank=True, upload_to='uploads', verbose_name='Empresa_Imatge'),
        ),
        migrations.AddField(
            model_name='centre',
            name='cod_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa'),
        ),
    ]
